spec_version: 4.0.0

info:
  name: mqtt-bridge
  title: mqtt-bridge
  description: mqtt-bridge
  version: 1.0.0

app:
  type: bridge
  bridge:
    language:
      type: python
      python:
        entry_point: mqtt_bridge:MQTTBridge
        requirements: requirements.txt

    configuration: {}
    metrics_map: []
